# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5855c0f8c4d74597dd95234835b47171325abc667773f74c6d05f3b1c187f35bf0814ff3646e60c44b8af5a7d641f36a991202f7dbf89a7064637e6529638175

test:
  secret_key_base: 2220da55998a866ec2f59a6fb6b975f7a34956f8eb8cad1548372d3b0ff4e51e987a62d6f205171990f7bc406c171db27e88e99bdc953373efaec0909f78a7a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
